### PR TITLE
Update metadata-eml.md

### PR DESCRIPTION
**Pull request by MathewBiddle**
adding suggested minimalistic acknowledgement statement for the support for MBON from federal agencies

### CODE REVIEW

**Comment by MathewBiddle** [comment]
@sformel-usgs Last week there was a message sent around to the MBON projects about providing a suggested minimalistic acknowledgement statement for the support for MBON from federal agencies. This PR adds that text to our [How-to guide for MBON metadata](https://ioos.github.io/mbon-docs/metadata-eml.html#project-data) under the **Funding:** section. 

I'm looking for your advice as to where a statement like this would fit into the metadata record.

**Review by sformel-usgs — APPROVED** [review]
This commit and general implementation seem appropriate to me.

**Comment by sformel-usgs** [comment]
@MathewBiddle not sure if I'm supposed to close this, or you.  But it's good to go!

**Comment by MathewBiddle** [comment]
Thanks @sformel-usgs !!

**Pull request merged**
