### PR TITLE
adding associated parties guidance

### LINKED ISSUE #19: Update how-to metadata guide for US MBON associatedParty
As discussed during the 12/13 MBON DMAC WG meeting, we will be adding "US MBON" as the `organizationName` for an additional `associatedParty`.

The `associatedParty` should be the person who worked with Abby to align the data to DarwinCore. You can find information about the associatedParty in this eml documentation: https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_associatedParty

The `role` can be **Processor** but that might not always be the case (?). We don't have a clear source for the roles, but the following ticket should help us identify where the source is:
* https://github.com/gbif/ipt/issues/1915

Finally, I have started a conversation with OceanExpert on creating an institution with the following information:

**Name:** United States Marine Biodiversity Observation Network
**Acronym:** US MBON
**Address:** 1315 East-West Highway, Silver Spring MD 20910
**Website:** https://ioos.noaa.gov/project/mbon/

### PR DESCRIPTION
**Pull request by MathewBiddle**
closes #19

@albenson-usgs mind taking a look?

### CODE REVIEW

**Comment by MathewBiddle** [comment]
See https://github.com/ioos/mbon-docs/blob/eml_page/_docs/metadata-eml.md#associated-parties

**Comment by AbbyBenson** [comment]
Thanks Matt! I wonder if distributor is more appropriate. Not sure that MBON is always providing content. I do feel like MBON is "an agent involved in the publishing/distribution chain of a dataset". Also wondering if **Affiliated Party** under the table is supposed to be **Associated Party**?

**Comment by MathewBiddle** [comment]
I agree on the `distributor` role. 

**Affiliated** vs **Associated** was a mistype on my end.

Both have been fixed. Expect a new commit soon.

**Comment by MathewBiddle** [comment]
https://github.com/ioos/mbon-docs/blob/eml_page/_docs/metadata-eml.md#associated-parties should be updated now.

**Review by AbbyBenson — APPROVED** [review]

**Pull request merged**
