### PR TITLE
adding diagram as mermaid

### LINKED ISSUE #40: create flowchart for MBON data flow +data.ioos.gov +data.gov etc
update https://github.com/ioos/mbon-docs/blob/gh-pages/_docs/images/MBON_Data_Flow.png

using mermaid to show how records get to data.ioos.us, noaa one stop, data.gov.

### PR DESCRIPTION
**Pull request by MathewBiddle**
closes #40

### CODE REVIEW

**Comment by MathewBiddle** [comment]
@laurabrenskelle mind taking a look to see if this works?

**Comment by MathewBiddle** [comment]
For reference, I followed the instructions at https://github.com/ioos/documentation-theme-jekyll/pull/16#issue-2088773574

**Comment by MathewBiddle** [comment]
@laurabrenskelle mind merging this if it looks good?

**Comment by laurabrenskelle** [comment]
Sure, yes. This looks good to me.

**Pull request merged**
