### PR TITLE
Documentation restructure

### LINKED ISSUE #4: change title of site
This site is documenting how to contribute to the MBON data portal, so we should update the title to clearly state that. 

Right now it's a little confusing having [this help site for the MBON portal](https://mbon.ioos.us/help/index.html) and [this MBON Portal documentation site](https://ioos.github.io/mbon-docs/). 

If we can merge the two together, that would be great! 

I think the sections [using the MBON portal](https://ioos.github.io/mbon-docs/#using-the-mbon-data-portal), [adding data to the map view](https://ioos.github.io/mbon-docs/#adding-to-the-map-view), and [how biodiversity products are created](https://ioos.github.io/mbon-docs/#how-biodiversity-data-products-are-created) should be in the [help site for the MBON portal](https://mbon.ioos.us/help/index.html#) as they are documenting specifics about the portal.

The site in this repository should be dedicated to providing documentation to the MBON projects on how to properly manage their biodiversity data. Not necessarily specific to the MBON portal. 

In short, let's change the title so it's clear what each page is documenting. Then, lets look at merging the documentation.

### LINKED ISSUE #9: turn off sidebar accordion
I see documentation [here](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_sidebar_navigation.html)

but no clue how to edit [sidebar_ioos.yml](https://github.com/ioos/mbon-docs/blob/gh-pages/_data/sidebars/sidebar_ioos.yml).

### PR DESCRIPTION
**Pull request by MathewBiddle**
closes:
* #4
* #9 
* Maybe #7

### CODE REVIEW

**Comment by MathewBiddle** [comment]
You can see the draft at https://mathewbiddle.github.io/mbon-docs/

**Comment by MathewBiddle** [comment]
@7yl4r Think this addresses the comments and is worthy of pushing to ioos.github.io?

**Comment by 7yl4r** [comment]
I think this looks good, yes. Many more pages! Too many? 😜

**Comment by MathewBiddle** [comment]
@staceybuckelew if you are okay with these changes, we can merge this and send it to the MBON DMAC WG for review.

**Comment by MathewBiddle** [comment]
@mwengren adding you for a red flag review. See draft at: https://mathewbiddle.github.io/mbon-docs/

**Pull request merged**
